parameters:
    rf.listener.maintenance.class: Rf\BlogBundle\Listener\Maintenance\MaintenanceListener
    rf.maintenance.controller.class: Rf\BlogBundle\Controller\MaintenanceController
    rf.config.class: Rf\BlogBundle\Utility\Config\YamlConfigContainer
    rf.config.twig.class: Rf\BlogBundle\Templating\Extension\YamlConfigExtension
    rf.welcome.class: Rf\BlogBundle\Utility\Welcome\WelcomeContainer
    rf.welcome.twig.class: Rf\BlogBundle\Templating\Extension\WelcomeExtension
    scribe.parser.swim.class: Rf\BlogBundle\Utility\Parser\Swim\SwimParser
    scribe.parser.swim.twig.class: Rf\BlogBundle\Templating\Extension\SwimExtension

services:
    rf.listener.maintenance:
        class:     "%rf.listener.maintenance.class%"
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: queryMaintenanceState }

    rf.maintenance.controller:
        class:     "%rf.maintenance.controller.class%"
        arguments: ["@service_container"]
        tags:
            - { name: maintenance.controller }

    rf.config:
        class:     "%rf.config.class%"
        arguments: ["@service_container"]
        tags:
            - { name: config.yml }

    rf.config.twig:
        class:     "%rf.config.twig.class%"
        arguments: ["@rf.config"]
        tags:
            - { name: twig.extension }

    rf.welcome:
        class:     "%rf.welcome.class%"
        arguments: ["@service_container"]
        tags:
            - { name: config.yml }

    rf.welcome.twig:
        class:     "%rf.welcome.twig.class%"
        arguments: ["@rf.welcome"]
        tags:
            - { name: twig.extension }

    scribe.parser.swim:
            class: %scribe.parser.swim.class%
            arguments: [ "@service_container" ]
            tags:
                - { name: parser.swim, alias: swim }

    scribe.parser.swim.twig:
        class:     "%scribe.parser.swim.twig.class%"
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }