parameters:
    rf.listener.maintenance.class: Rf\BlogBundle\Listener\Maintenance\MaintenanceListener
    rf.config.class: Rf\BlogBundle\Utility\Config\YamlConfigContainer
    rf.config.twig.class: Rf\BlogBundle\Templating\Extension\YamlConfigExtension

services:
    rf.listener.maintenance:
        class:     "%rf.listener.maintenance.class%"
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: queryMaintenanceState }

    rf.config:
        class:     "%rf.config.class%"
        arguments: ["@service_container"]
        tags:
            - { name: config.yml }

    rf.config.twig:
        class:     "%rf.config.twig.class%"
        arguments: ["@rf.config"]
        tags:
            - { name: twig.extension }