rf_blog:

    maintenance_mode:
        enable: false
        mode: all
        bundles: ['RfBlogBundle']

    html:
        title_pre: ~
        title_post: '[robfrawley.com]'
        charset: UTF-8
        lang: en

    brand_name: Rob Frawley 2nd

    footer_credit: 'Designed and maintained by {~a:http://inserr.at/ Inserrat Technologies}.'

    date_format: 'l, F j'