rf_blog:

    maintenance_mode:
        enable: false
        mode: all
        bundles: []

    html:
        title_pre: ~
        title_post: '[robfrawley.com]'
        charset: UTF-8
        lang: en

    brand_name: Rob Frawley 2nd
    brand_footer: '&copy; 2013 Rob Frawley 2nd'

    date_format: 'l, F j'