rf_root:
    path:     /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /feature
        permanent: true

rf_blog:
    resource: "@RfBlogBundle/Resources/config/routing.yml"
    prefix:   /